name: lando-d8-phpunit
recipe: drupal8
config:
  php: '7.3'
  webroot: docroot
  drush: 9
  xdebug: true
  conf:
    php: .vscode/php.ini

services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT && ./bin/phing lando-build"
      - "phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer"
      - "/app/vendor/squizlabs/php_codesniffer/bin/phpcs --config-set installed_paths /app/vendor/drupal/coder/coder_sniffer"

tooling:
  install:
    description: Install Application
    cmd:
      - cd $LANDO_WEBROOT && drush si --db-url=mysql://drupal8:drupal8@database:3306/drupal8 --locale='en' --site-name='D8 and TDD' --site-mail='admin@example.com' --account-name='admin' --account-mail='admin@example.com' --account-pass='admin' --yes
    service: appserver
  phpcs:
    service: appserver
    cmd: "/app/vendor/squizlabs/php_codesniffer/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md"
    description: Run phpcs for given folder or file.
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
